services:
  - name: rabbitmq:management
    alias: rabbitmq

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: 5672
  RABBITMQ_DEFAULT_USER: doclib
  RABBITMQ_DEFAULT_PASS: doclib
  RABBITMQ_DEFAULT_VHOST: "/"


cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - test
  - publish
  - release
  - docs

default:
  image: registry.mdcatapult.io/informatics/docker-images/ci/python:3.7
  before_script:
    - >
      pip install -r requirements.txt --trusted-host=nexus.wopr.inf.mdc
      --index=https://$NEXUS_USERNAME:$NEXUS_PASSWORD@nexus.wopr.inf.mdc/repository/pypi-all/pypi
      --index-url=https://$NEXUS_USERNAME:$NEXUS_PASSWORD@nexus.wopr.inf.mdc/repository/pypi-all/simple

lint:
  stage: test
  tags:
    - wopr
  script:
    - pylint --rcfile=.pylintrc src
  except:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

test:
  stage: test
  tags:
    - wopr
  script:
    - pytest --cov-report term:skip-covered --cov=src tests/
  coverage: '/TOTAL.*\s+(\d+%)$/'

publish-stable:
  stage: publish
  tags:
    - wopr
  script:
    - python setup.py sdist bdist_wheel
    - twine upload --cert "$WOPR_CRT" -u $NEXUS_USERNAME -p $NEXUS_PASSWORD --repository-url https://nexus.wopr.inf.mdc/repository/pypi-stable/ dist/*
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

publish-unstable:
  stage: publish
  tags:
    - wopr
  script:
    - python setup.py sdist bdist_wheel
    - twine upload --cert "$WOPR_CRT" -u $NEXUS_USERNAME -p $NEXUS_PASSWORD --repository-url https://nexus.wopr.inf.mdc/repository/pypi-unstable/ dist/*
  except:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

release:
  stage: release
  tags:
    - wopr
  before_script:
    - ''
  script:
    - /scripts/release.sh src
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

pages:
  stage: docs
  tags:
    - wopr
  script:
    - pip install pdoc3
    - pdoc --html src -o public/
  artifacts:
    paths:
    - public
  only:
    - master